// ignore_for_file: deprecated_member_use_from_same_package
import 'dart:html';

import '../synthetic_event.dart';
import '../synthetic_event_wrappers.dart' as event_wrappers;

/// A cross-browser wrapper around the browser's [nativeEvent].
///
/// It has the same interface as the browser's native event, including [stopPropagation] and [preventDefault], except
/// the events work identically across all browsers.
///
/// See: <https://facebook.github.io/react/docs/events.html#syntheticevent>
///
/// __Deprecated.__ Use [SyntheticEventV2] instead.
@Deprecated('6.0.0')
class SyntheticEvent {
  /// Indicates whether the [Event] bubbles up through the DOM or not.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/bubbles>
  final bool bubbles;

  /// Indicates whether the [Event] is cancelable or not.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelable>
  final bool cancelable;

  /// Identifies the current target for the event, as the [Event] traverses the DOM.
  ///
  /// It always refers to the [Element] the [Event] handler has been attached to as opposed to [target] which identifies
  /// the [Element] on which the [Event] occurred.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget>
  final /*DOMEventTarget*/ currentTarget;

  bool _defaultPrevented;

  dynamic _preventDefault;

  /// Indicates whether or not [preventDefault] was called on the event.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented>
  bool get defaultPrevented => _defaultPrevented;

  /// Cancels the [Event] if it is [cancelable], without stopping further propagation of the event.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault>
  void preventDefault() {
    _defaultPrevented = true;
    _preventDefault();
  }

  /// Prevents further propagation of the current event.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation>
  final dynamic stopPropagation;

  /// Indicates which phase of the [Event] flow is currently being evaluated.
  ///
  /// Possible values:
  ///
  /// > [Event.CAPTURING_PHASE] (1) - The [Event] is being propagated through the [target]'s ancestor objects. This
  /// process starts with the Window, then [HtmlDocument], then the [HtmlHtmlElement], and so on through the [Element]s
  /// until the [target]'s parent is reached. Event listeners registered for capture mode when
  /// [EventTarget.addEventListener] was called are triggered during this phase.
  ///
  /// > [Event.AT_TARGET] (2) - The [Event] has arrived at the [target]. Event listeners registered for this phase are
  /// called at this time. If [bubbles] is `false`, processing the [Event] is finished after this phase is complete.
  ///
  /// > [Event.BUBBLING_PHASE] (3) - The [Event] is propagating back up through the [target]'s ancestors in reverse
  /// order, starting with the parent, and eventually reaching the containing Window. This is known as bubbling, and
  /// occurs only if [bubbles] is `true`. [Event] listeners registered for this phase are triggered during this process.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/eventPhase>
  final num eventPhase;

  /// Is `true` when the [Event] was generated by a user action, and `false` when the [Event] was created or modified
  /// by a script or dispatched via [Event.dispatchEvent].
  ///
  /// __Read Only__
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted>
  final bool isTrusted;

  /// Native browser event that [SyntheticEvent] wraps around.
  final /*DOMEvent*/ nativeEvent;

  /// A reference to the object that dispatched the event. It is different from [currentTarget] when the [Event]
  /// handler is called when [eventPhase] is [Event.BUBBLING_PHASE] or [Event.CAPTURING_PHASE].
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/target>
  final /*DOMEventTarget*/ target;

  /// Returns the [Time] (in milliseconds) at which the [Event] was created.
  ///
  /// _Starting with Chrome 49, returns a high-resolution monotonic time instead of epoch time._
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp>
  final num timeStamp;

  /// Returns a string containing the type of event. It is set when the [Event] is constructed and is the name commonly
  /// used to refer to the specific event.
  ///
  /// See: <https://developer.mozilla.org/en-US/docs/Web/API/Event/type>
  final String type;

  SyntheticEvent(
      this.bubbles,
      this.cancelable,
      this.currentTarget,
      this._defaultPrevented,
      this._preventDefault,
      this.stopPropagation,
      this.eventPhase,
      this.isTrusted,
      this.nativeEvent,
      this.target,
      this.timeStamp,
      this.type) {}
}

/// Wrapper for [SyntheticEvent].
///
/// __Deprecated.__ Use [syntheticEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticEvent syntheticEventFactory(event_wrappers.SyntheticEvent e) {
  return new SyntheticEvent(e.bubbles, e.cancelable, e.currentTarget, e.defaultPrevented, () => e.preventDefault(),
      () => e.stopPropagation(), e.eventPhase, e.isTrusted, e.nativeEvent, e.target, e.timeStamp, e.type);
}

/// __Deprecated.__ Use [SyntheticClipboardEventV2] instead.
@Deprecated('6.0.0')
class SyntheticClipboardEvent extends SyntheticEvent {
  final clipboardData;

  SyntheticClipboardEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.clipboardData,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticClipboardEvent].
///
/// __Deprecated.__ Use [syntheticClipboardEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticClipboardEvent syntheticClipboardEventFactory(event_wrappers.SyntheticClipboardEvent e) {
  return new SyntheticClipboardEvent(
      e.bubbles,
      e.cancelable,
      e.currentTarget,
      e.defaultPrevented,
      () => e.preventDefault(),
      () => e.stopPropagation(),
      e.eventPhase,
      e.isTrusted,
      e.nativeEvent,
      e.target,
      e.timeStamp,
      e.type,
      e.clipboardData);
}

/// __Deprecated.__ Use [SyntheticKeyboardEventV2] instead.
@Deprecated('6.0.0')
class SyntheticKeyboardEvent extends SyntheticEvent implements KeyModifierEventInterface {
  @override
  final bool altKey;
  final String char;
  @override
  final bool ctrlKey;
  final String locale;
  final num location;
  final String key;
  @override
  final bool metaKey;
  final bool repeat;
  @override
  final bool shiftKey;
  final num keyCode;
  final num charCode;

  SyntheticKeyboardEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.altKey,
    this.char,
    this.charCode,
    this.ctrlKey,
    this.locale,
    this.location,
    this.key,
    this.keyCode,
    this.metaKey,
    this.repeat,
    this.shiftKey,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticKeyboardEvent].
///
/// __Deprecated.__ Use [syntheticKeyboardEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticKeyboardEvent syntheticKeyboardEventFactory(event_wrappers.SyntheticKeyboardEvent e) {
  return new SyntheticKeyboardEvent(
      e.bubbles,
      e.cancelable,
      e.currentTarget,
      e.defaultPrevented,
      () => e.preventDefault(),
      () => e.stopPropagation(),
      e.eventPhase,
      e.isTrusted,
      e.nativeEvent,
      e.target,
      e.timeStamp,
      e.type,
      e.altKey,
      e.char,
      e.charCode,
      e.ctrlKey,
      e.locale,
      e.location,
      e.key,
      e.keyCode,
      e.metaKey,
      e.repeat,
      e.shiftKey);
}

/// __Deprecated.__ Use [SyntheticFocusEventV2] instead.
@Deprecated('6.0.0')
class SyntheticFocusEvent extends SyntheticEvent {
  final /*DOMEventTarget*/ relatedTarget;

  SyntheticFocusEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.relatedTarget,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticFocusEvent].
///
/// __Deprecated.__ Use [syntheticFocusEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticFocusEvent syntheticFocusEventFactory(event_wrappers.SyntheticFocusEvent e) {
  return new SyntheticFocusEvent(
      e.bubbles,
      e.cancelable,
      e.currentTarget,
      e.defaultPrevented,
      () => e.preventDefault(),
      () => e.stopPropagation(),
      e.eventPhase,
      e.isTrusted,
      e.nativeEvent,
      e.target,
      e.timeStamp,
      e.type,
      e.relatedTarget);
}

/// __Deprecated.__ Use [SyntheticFormEventV2] instead.
@Deprecated('6.0.0')
class SyntheticFormEvent extends SyntheticEvent {
  SyntheticFormEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticFormEvent].
///
/// __Deprecated.__ Use [syntheticFormEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticFormEvent syntheticFormEventFactory(event_wrappers.SyntheticFormEvent e) {
  return new SyntheticFormEvent(e.bubbles, e.cancelable, e.currentTarget, e.defaultPrevented, () => e.preventDefault(),
      () => e.stopPropagation(), e.eventPhase, e.isTrusted, e.nativeEvent, e.target, e.timeStamp, e.type);
}

/// __Deprecated.__ Use [SyntheticDataTransferV2] instead.
@Deprecated('6.0.0')
class SyntheticDataTransfer {
  final String dropEffect;
  final String effectAllowed;
  final List files;
  final List<String> types;

  SyntheticDataTransfer(this.dropEffect, this.effectAllowed, this.files, this.types);
}

/// Wrapper for [SyntheticDataTransfer].
///
/// __Deprecated.__ Use [syntheticDataTransferV2Factory] instead.
@Deprecated('6.0.0')
SyntheticDataTransfer syntheticDataTransferFactory(event_wrappers.SyntheticDataTransfer dt) {
  if (dt == null) return null;
  List<File> files = [];
  if (dt.files != null) {
    for (int i = 0; i < dt.files.length; i++) {
      files.add(dt.files[i]);
    }
  }
  List<String> types = [];
  if (dt.types != null) {
    for (int i = 0; i < dt.types.length; i++) {
      types.add(dt.types[i]);
    }
  }
  var effectAllowed;
  var dropEffect;

  try {
    // Works around a bug in IE where dragging from outside the browser fails.
    // Trying to access this property throws the error "Unexpected call to method or property access.".
    effectAllowed = dt.effectAllowed;
  } catch (exception) {
    effectAllowed = 'uninitialized';
  }

  try {
    // For certain types of drag events in IE (anything but ondragenter, ondragover, and ondrop), this fails.
    // Trying to access this property throws the error "Unexpected call to method or property access.".
    dropEffect = dt.dropEffect;
  } catch (exception) {
    dropEffect = 'none';
  }

  return new SyntheticDataTransfer(dropEffect, effectAllowed, files, types);
}

/// __Deprecated.__ Use [SyntheticMouseEventV2] instead.
@Deprecated('6.0.0')
class SyntheticMouseEvent extends SyntheticEvent implements KeyModifierEventInterface {
  @override
  final bool altKey;
  final num button;
  final num buttons;
  final num clientX;
  final num clientY;
  @override
  final bool ctrlKey;
  final SyntheticDataTransfer dataTransfer;
  @override
  final bool metaKey;
  final num pageX;
  final num pageY;
  final /*DOMEventTarget*/ relatedTarget;
  final num screenX;
  final num screenY;
  @override
  final bool shiftKey;

  SyntheticMouseEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.altKey,
    this.button,
    this.buttons,
    this.clientX,
    this.clientY,
    this.ctrlKey,
    this.dataTransfer,
    this.metaKey,
    this.pageX,
    this.pageY,
    this.relatedTarget,
    this.screenX,
    this.screenY,
    this.shiftKey,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticMouseEvent].
///
/// __Deprecated.__ Use [syntheticMouseEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticMouseEvent syntheticMouseEventFactory(event_wrappers.SyntheticMouseEvent e) {
  SyntheticDataTransfer dt = syntheticDataTransferFactory(e.dataTransfer);
  return new SyntheticMouseEvent(
    e.bubbles,
    e.cancelable,
    e.currentTarget,
    e.defaultPrevented,
    () => e.preventDefault(),
    () => e.stopPropagation(),
    e.eventPhase,
    e.isTrusted,
    e.nativeEvent,
    e.target,
    e.timeStamp,
    e.type,
    e.altKey,
    e.button,
    e.buttons,
    e.clientX,
    e.clientY,
    e.ctrlKey,
    dt,
    e.metaKey,
    e.pageX,
    e.pageY,
    e.relatedTarget,
    e.screenX,
    e.screenY,
    e.shiftKey,
  );
}

/// __Deprecated.__ Use [SyntheticPointerEventV2] instead.
@Deprecated('6.0.0')
class SyntheticPointerEvent extends SyntheticEvent {
  final num pointerId;
  final num width;
  final num height;
  final num pressure;
  final num tangentialPressure;
  final num tiltX;
  final num tiltY;
  final num twist;
  final String pointerType;
  final bool isPrimary;

  SyntheticPointerEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.pointerId,
    this.width,
    this.height,
    this.pressure,
    this.tangentialPressure,
    this.tiltX,
    this.tiltY,
    this.twist,
    this.pointerType,
    this.isPrimary,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticPointerEvent].
///
/// __Deprecated.__ Use [syntheticPointerEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticPointerEvent syntheticPointerEventFactory(event_wrappers.SyntheticPointerEvent e) {
  return new SyntheticPointerEvent(
    e.bubbles,
    e.cancelable,
    e.currentTarget,
    e.defaultPrevented,
    () => e.preventDefault(),
    () => e.stopPropagation(),
    e.eventPhase,
    e.isTrusted,
    e.nativeEvent,
    e.target,
    e.timeStamp,
    e.type,
    e.pointerId,
    e.width,
    e.height,
    e.pressure,
    e.tangentialPressure,
    e.tiltX,
    e.tiltY,
    e.twist,
    e.pointerType,
    e.isPrimary,
  );
}

/// __Deprecated.__ Use [SyntheticTouchEventV2] instead.
@Deprecated('6.0.0')
class SyntheticTouchEvent extends SyntheticEvent implements KeyModifierEventInterface {
  @override
  final bool altKey;
  final /*DOMTouchList*/ changedTouches;
  @override
  final bool ctrlKey;
  @override
  final bool metaKey;
  @override
  final bool shiftKey;
  final /*DOMTouchList*/ targetTouches;
  final /*DOMTouchList*/ touches;

  SyntheticTouchEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.altKey,
    this.changedTouches,
    this.ctrlKey,
    this.metaKey,
    this.shiftKey,
    this.targetTouches,
    this.touches,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticTouchEvent].
///
/// __Deprecated.__ Use [syntheticTouchEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticTouchEvent syntheticTouchEventFactory(event_wrappers.SyntheticTouchEvent e) {
  return new SyntheticTouchEvent(
    e.bubbles,
    e.cancelable,
    e.currentTarget,
    e.defaultPrevented,
    () => e.preventDefault(),
    () => e.stopPropagation(),
    e.eventPhase,
    e.isTrusted,
    e.nativeEvent,
    e.target,
    e.timeStamp,
    e.type,
    e.altKey,
    e.changedTouches,
    e.ctrlKey,
    e.metaKey,
    e.shiftKey,
    e.targetTouches,
    e.touches,
  );
}

/// __Deprecated.__ Use [SyntheticTransitionEventV2] instead.
@Deprecated('6.0.0')
class SyntheticTransitionEvent extends SyntheticEvent {
  final String propertyName;
  final num elapsedTime;
  final String pseudoElement;

  SyntheticTransitionEvent(
      bubbles,
      cancelable,
      currentTarget,
      _defaultPrevented,
      _preventDefault,
      stopPropagation,
      eventPhase,
      isTrusted,
      nativeEvent,
      target,
      timeStamp,
      type,
      this.propertyName,
      this.elapsedTime,
      this.pseudoElement)
      : super(bubbles, cancelable, currentTarget, _defaultPrevented, _preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticTransitionEvent].
///
/// __Deprecated.__ Use [syntheticTransitionEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticTransitionEvent syntheticTransitionEventFactory(event_wrappers.SyntheticTransitionEvent e) {
  return new SyntheticTransitionEvent(
    e.bubbles,
    e.cancelable,
    e.currentTarget,
    e.defaultPrevented,
    () => e.preventDefault(),
    () => e.stopPropagation(),
    e.eventPhase,
    e.isTrusted,
    e.nativeEvent,
    e.target,
    e.timeStamp,
    e.type,
    e.propertyName,
    e.elapsedTime,
    e.pseudoElement,
  );
}

/// __Deprecated.__ Use [SyntheticAnimationEventV2] instead.
@Deprecated('6.0.0')
class SyntheticAnimationEvent extends SyntheticEvent {
  final String animationName;
  final num elapsedTime;
  final String pseudoElement;

  SyntheticAnimationEvent(
      bubbles,
      cancelable,
      currentTarget,
      _defaultPrevented,
      _preventDefault,
      stopPropagation,
      eventPhase,
      isTrusted,
      nativeEvent,
      target,
      timeStamp,
      type,
      this.animationName,
      this.elapsedTime,
      this.pseudoElement)
      : super(bubbles, cancelable, currentTarget, _defaultPrevented, _preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticAnimationEvent].
///
/// __Deprecated.__ Use [syntheticAnimationEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticAnimationEvent syntheticAnimationEventFactory(event_wrappers.SyntheticAnimationEvent e) {
  return new SyntheticAnimationEvent(
    e.bubbles,
    e.cancelable,
    e.currentTarget,
    e.defaultPrevented,
    () => e.preventDefault(),
    () => e.stopPropagation(),
    e.eventPhase,
    e.isTrusted,
    e.nativeEvent,
    e.target,
    e.timeStamp,
    e.type,
    e.animationName,
    e.elapsedTime,
    e.pseudoElement,
  );
}

/// __Deprecated.__ Use [SyntheticUIEventV2] instead.
@Deprecated('6.0.0')
class SyntheticUIEvent extends SyntheticEvent {
  final num detail;
  final /*DOMAbstractView*/ view;

  SyntheticUIEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool _defaultPrevented,
    dynamic _preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.detail,
    this.view,
  ) : super(bubbles, cancelable, currentTarget, _defaultPrevented, _preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticUIEvent].
///
/// __Deprecated.__ Use [syntheticUIEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticUIEvent syntheticUIEventFactory(event_wrappers.SyntheticUIEvent e) {
  return new SyntheticUIEvent(
    e.bubbles,
    e.cancelable,
    e.currentTarget,
    e.defaultPrevented,
    () => e.preventDefault(),
    () => e.stopPropagation(),
    e.eventPhase,
    e.isTrusted,
    e.nativeEvent,
    e.target,
    e.timeStamp,
    e.type,
    e.detail,
    e.view,
  );
}

/// __Deprecated.__ Use [SyntheticWheelEventV2] instead.
@Deprecated('6.0.0')
class SyntheticWheelEvent extends SyntheticEvent {
  final num deltaX;
  final num deltaMode;
  final num deltaY;
  final num deltaZ;

  SyntheticWheelEvent(
    bool bubbles,
    bool cancelable,
    dynamic currentTarget,
    bool defaultPrevented,
    dynamic preventDefault,
    dynamic stopPropagation,
    num eventPhase,
    bool isTrusted,
    dynamic nativeEvent,
    dynamic target,
    num timeStamp,
    String type,
    this.deltaX,
    this.deltaMode,
    this.deltaY,
    this.deltaZ,
  ) : super(bubbles, cancelable, currentTarget, defaultPrevented, preventDefault, stopPropagation, eventPhase,
            isTrusted, nativeEvent, target, timeStamp, type) {}
}

/// Wrapper for [SyntheticWheelEvent].
///
/// __Deprecated.__ Use [syntheticWheelEventV2Factory] instead.
@Deprecated('6.0.0')
SyntheticWheelEvent syntheticWheelEventFactory(event_wrappers.SyntheticWheelEvent e) {
  return new SyntheticWheelEvent(
    e.bubbles,
    e.cancelable,
    e.currentTarget,
    e.defaultPrevented,
    () => e.preventDefault(),
    () => e.stopPropagation(),
    e.eventPhase,
    e.isTrusted,
    e.nativeEvent,
    e.target,
    e.timeStamp,
    e.type,
    e.deltaX,
    e.deltaMode,
    e.deltaY,
    e.deltaZ,
  );
}
