name: Test Workflow

on:
  workflow_call:
    inputs:
      sdk:
        required: true
        type: string
        default: 2.19.6

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete Dart-2-only files when running on Dart 3
        if: ${{ inputs.sdk != '2.19.6' }}
        run: |
          ./tool/delete_dart_2_only_files.sh

  checks:
    needs: pre
    uses: Workiva/gha-dart-oss/.github/workflows/checks.yaml@v0.1.11
    with:
      additional-checks: |
        no_entrypoint_imports
      sdk: ${{ inputs.sdk }}
      format-check: ${{ inputs.sdk == '2.19.6' }}

  test:
    runs-on: ubuntu-latest
    needs: pre
    strategy:
      fail-fast: false
      matrix:
        react: [ 17, 18 ]
    steps:
      - uses: actions/checkout@v2
      - id: setup-dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ inputs.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Switch to React 17 Test HTML
        if: ${{ matrix.react == 17 }}
        run: |
          mv test/templates/html_template.html test/templates/html_template-old.html
          mv test/templates/html_template-react17.html test/templates/html_template.html

      - id: install
        name: Install dependencies
        run: dart pub get

      - name: Run tests (DDC)
        run: |
          dart run build_runner test --delete-conflicting-outputs -- --preset dartdevc --preset=react${{ matrix.react }}
        if: always() && steps.install.outcome == 'success'
        timeout-minutes: 8

      - name: Run tests (dart2js)
        run: |
          dart run build_runner test --delete-conflicting-outputs --release -- --preset dart2js --preset=react${{ matrix.react }}
        if: always() && steps.install.outcome == 'success'
        timeout-minutes: 8
