name: CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

jobs:
  checks:
    strategy:
      matrix:
        sdk: [ 2.19.6, stable ]
    uses: ./.github/workflows/test.yml
    with:
      sdk: ${{ matrix.sdk }}

  # Run as a separate job outside the Dart SDK matrix below,
  # since we can only emit a single SBOM.
  build:
    uses: Workiva/gha-dart-oss/.github/workflows/build.yaml@v0.1.11
    with:
      sdk: 2.19.6 # This version doesn't matter so long as it resolves.
